-- bookshelf_lang.lua
-- Canonicalise ebook language metadata for the Languages grouping/filter.
--
-- Ebook <dc:language> values are a mess across a real library: 2-letter
-- ISO 639-1 codes ("en"), 3-letter ISO 639-3 codes ("eng"), region-tagged
-- BCP47 tags ("en-US", "zh-Hans"), and occasionally full names ("English").
-- Grouping on the raw value splits one language across several cards and
-- labels them with cryptic codes. canonical() folds every spelling of a
-- language onto a single key and hands back a friendly, localised label.
--
-- Names come from KOReader's ui/data/isolanguage (localised, maintained).
-- That module keeps its code tables private and only exposes a 3-letter
-- lookup, so we bundle the small, frozen ISO 639-1 -> 639-3 bridge here and
-- derive the name<->code reverse lookup from KOReader at load.

local M = {}

-- ISO 639-1 (alpha-2) -> ISO 639-3 (alpha-3). Generated by inverting
-- KOReader's iso_bcp47_map, so every value resolves to a name via
-- getLocalizedLanguage. Reference data: stable, not expected to change.
local ALPHA2_TO_ALPHA3 = {
    aa = "aar", af = "afr", ar = "ara", as = "asm", az = "aze", ba = "bak",
    be = "bel", bg = "bul", bn = "ben", bo = "bod", br = "bre", cs = "ces",
    cu = "chu", cy = "cym", da = "dan", de = "deu", dv = "div", el = "ell",
    en = "eng", eo = "epo", es = "spa", et = "est", eu = "eus", fa = "fas",
    fi = "fin", fo = "fao", fr = "fra", fy = "fry", ga = "gle", gd = "gla",
    gl = "glg", gv = "glv", ha = "hau", he = "heb", hi = "hin", ht = "hat",
    hu = "hun", hy = "hye", ia = "ina", id = "ind", io = "ido", is = "isl",
    it = "ita", ja = "jpn", jv = "jav", ka = "kat", ki = "kik", kk = "kaz",
    kl = "kal", km = "khm", kn = "kan", ko = "kor", ks = "kas", ku = "kur",
    kw = "cor", ky = "kir", la = "lat", lb = "ltz", lo = "lao", lt = "lit",
    lv = "lav", mg = "mlg", mh = "mah", mi = "mri", mk = "mkd", ml = "mal",
    mn = "mon", mr = "mar", ms = "msa", mt = "mlt", my = "mya", nb = "nob",
    nl = "nld", nn = "nno", no = "nor", nv = "nav", oc = "oci", om = "orm",
    pa = "pan", pi = "pli", pl = "pol", ps = "pus", pt = "por", qu = "que",
    rm = "roh", ro = "ron", ru = "rus", sa = "san", sh = "hbs", sk = "slk",
    sl = "slv", sq = "sqi", sr = "srp", ss = "ssw", su = "sun", sv = "swe",
    sw = "swa", ta = "tam", te = "tel", tg = "tgk", th = "tha", tl = "tgl",
    tr = "tur", tt = "tat", ug = "uig", uk = "ukr", ur = "urd", uz = "uzb",
    vi = "vie", vo = "vol", wa = "wln", xh = "xho", yi = "yid", yo = "yor",
    za = "zha", zh = "zho", zu = "zul",
}

-- KOReader's localised name lookup. Optional: if the module is unavailable
-- (odd build/test context) we degrade to using the code itself as the label.
local _iso = nil
do
    local ok, mod = pcall(require, "ui/data/isolanguage")
    if ok then _iso = mod end
end

local function _localizedName(iso3)
    if _iso and _iso.getLocalizedLanguage then
        local ok, name = pcall(_iso.getLocalizedLanguage, _iso, iso3)
        if ok and name then return name end
    end
    return iso3
end

-- name (lowercased) -> iso3, built from the codes we bridge. Lets a book that
-- declares "English" land on the same key as one declaring "en". Localised to
-- the current UI language, since the names come from KOReader.
local _NAME_TO_ALPHA3
local function _nameToAlpha3()
    if _NAME_TO_ALPHA3 then return _NAME_TO_ALPHA3 end
    local map = {}
    for _alpha2, iso3 in pairs(ALPHA2_TO_ALPHA3) do
        local name = _localizedName(iso3)
        if type(name) == "string" and name ~= iso3 then
            map[name:lower()] = iso3
        end
    end
    _NAME_TO_ALPHA3 = map
    return map
end

local function _trim(s) return (s:gsub("^%s+", ""):gsub("%s+$", "")) end

-- canonical(raw): returns (key, label) for a language value, or nil for an
-- empty/absent value (the caller owns the "Unknown" bucket).
--   key   - stable grouping key; every spelling of one language shares it
--   label - friendly, localised display name (falls back to the raw value)
function M.canonical(raw)
    if type(raw) ~= "string" then return nil end
    local trimmed = _trim(raw)
    if trimmed == "" then return nil end
    local lower = trimmed:lower()

    -- Full-name match first ("english", "modern greek") before we strip
    -- anything region-like off a code.
    local by_name = _nameToAlpha3()[lower]
    if by_name then return by_name, _localizedName(by_name) end

    -- Primary subtag: drop region/script ("en-US" -> "en", "zh_Hans" -> "zh").
    local primary = lower:match("^([^-_]+)") or lower
    if #primary == 2 and ALPHA2_TO_ALPHA3[primary] then
        local iso3 = ALPHA2_TO_ALPHA3[primary]
        return iso3, _localizedName(iso3)
    end
    if #primary == 3 and primary:match("^%a%a%a$") then
        return primary, _localizedName(primary)
    end

    -- Unresolved: keep a normalised key (so case/region variants still merge)
    -- and show the book's own value as the best-effort label.
    return primary, trimmed
end

return M
